"""empty message

Revision ID: 6ba386495323
Revises: d9bfe8d1b89e
Create Date: 2025-08-18 20:23:55.063401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba386495323'
down_revision = 'd9bfe8d1b89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.alter_column('user_from_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_to_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.alter_column('user_to_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_from_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
