"""empty message

Revision ID: 816564dd8869
Revises: e7b12f0ddfa6
Create Date: 2025-08-19 00:05:26.767914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816564dd8869'
down_revision = 'e7b12f0ddfa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_author_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comment_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_post_id_fkey', 'user', ['post_id'], ['id'])
        batch_op.create_foreign_key('comment_author_id_fkey', 'post', ['author_id'], ['id'])

    # ### end Alembic commands ###
