"""empty message

Revision ID: 9030f0950933
Revises: 48dd202ac3f1
Create Date: 2025-08-16 14:29:45.596979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9030f0950933'
down_revision = '48dd202ac3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_Name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('user_firstName_key', type_='unique')
        batch_op.drop_constraint('user_lastName_key', type_='unique')
        batch_op.create_unique_constraint(None, ['first_Name'])
        batch_op.create_unique_constraint(None, ['last_name'])
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_lastName_key', ['lastName'])
        batch_op.create_unique_constraint('user_firstName_key', ['firstName'])
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_Name')

    # ### end Alembic commands ###
