"""empty message

Revision ID: a4da5f3747b4
Revises: 70a9b773f4cb
Create Date: 2025-08-16 15:51:47.191323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4da5f3747b4'
down_revision = '70a9b773f4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('content', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
