"""empty message

Revision ID: e4b547dd95f6
Revises: e9469734aa50
Create Date: 2025-08-16 00:20:29.962870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b547dd95f6'
down_revision = 'e9469734aa50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_to_id')

    # ### end Alembic commands ###
