"""empty message

Revision ID: e9469734aa50
Revises: 54d6a4a7da12
Create Date: 2025-08-16 00:18:24.153175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9469734aa50'
down_revision = '54d6a4a7da12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_from_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_from_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_from_id')

    # ### end Alembic commands ###
